name: Deploy Resourcepack to Edenor Arena

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compress resourcepack directory
        run: |
          cd Pack
          zip -r ../arena.zip .
          cd ..
          FILESIZE=$(wc -c < arena.zip)
          if [ $FILESIZE -gt 262144000 ]; then # 250 MiB in bytes
            echo "Error: Resourcepack size exceeds 250 MiB limit."
            exit 1
          fi

      - name: Deploy to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "arena.zip"
          target: "/var/www/files/"
